export class OBJExporter {
  static export(meshes) {
    let output = '# L-System 3D Plant - OBJ Export\n';
    output += '# Generated by L-System Generator\n';
    output += `# Date: ${new Date().toISOString()}\n\n`;

    let vertexIndex = 1;
    let objIndex = 1;

    for (const mesh of meshes) {
      const geometry = mesh.geometry;
      const matrix = mesh.matrixWorld;

      if (!geometry.attributes.position) continue;

      const positions = geometry.attributes.position.array;
      const normals = geometry.attributes.normal ? geometry.attributes.normal.array : null;
      const uvs = geometry.attributes.uv ? geometry.attributes.uv.array : null;
      const indices = geometry.index ? geometry.index.array : null;

      output += `o Object_${objIndex}\n`;

      const localVertices = [];
      for (let i = 0; i < positions.length; i += 3) {
        const v = {
          x: positions[i],
          y: positions[i + 1],
          z: positions[i + 2]
        };
        const transformed = this.transformVertex(v, matrix);
        localVertices.push(transformed);
        output += `v ${transformed.x.toFixed(6)} ${transformed.y.toFixed(6)} ${transformed.z.toFixed(6)}\n`;
      }

      if (normals) {
        for (let i = 0; i < normals.length; i += 3) {
          const n = {
            x: normals[i],
            y: normals[i + 1],
            z: normals[i + 2]
          };
          const transformed = this.transformNormal(n, matrix);
          output += `vn ${transformed.x.toFixed(6)} ${transformed.y.toFixed(6)} ${transformed.z.toFixed(6)}\n`;
        }
      }

      if (uvs) {
        for (let i = 0; i < uvs.length; i += 2) {
          output += `vt ${uvs[i].toFixed(6)} ${uvs[i + 1].toFixed(6)}\n`;
        }
      }

      if (indices) {
        for (let i = 0; i < indices.length; i += 3) {
          const a = indices[i] + vertexIndex;
          const b = indices[i + 1] + vertexIndex;
          const c = indices[i + 2] + vertexIndex;
          if (normals && uvs) {
            output += `f ${a}/${a}/${a} ${b}/${b}/${b} ${c}/${c}/${c}\n`;
          } else if (normals) {
            output += `f ${a}//${a} ${b}//${b} ${c}//${c}\n`;
          } else if (uvs) {
            output += `f ${a}/${a} ${b}/${b} ${c}/${c}\n`;
          } else {
            output += `f ${a} ${b} ${c}\n`;
          }
        }
      } else {
        for (let i = 0; i < positions.length / 3; i += 3) {
          const a = i + vertexIndex;
          const b = i + 1 + vertexIndex;
          const c = i + 2 + vertexIndex;
          if (normals && uvs) {
            output += `f ${a}/${a}/${a} ${b}/${b}/${b} ${c}/${c}/${c}\n`;
          } else if (normals) {
            output += `f ${a}//${a} ${b}//${b} ${c}//${c}\n`;
          } else if (uvs) {
            output += `f ${a}/${a} ${b}/${b} ${c}/${c}\n`;
          } else {
            output += `f ${a} ${b} ${c}\n`;
          }
        }
      }

      vertexIndex += positions.length / 3;
      objIndex++;
      output += '\n';
    }

    return output;
  }

  static transformVertex(v, matrix) {
    const e = matrix.elements;
    const x = v.x, y = v.y, z = v.z;
    const w = e[3] * x + e[7] * y + e[11] * z + e[15];
    return {
      x: (e[0] * x + e[4] * y + e[8] * z + e[12]) / w,
      y: (e[1] * x + e[5] * y + e[9] * z + e[13]) / w,
      z: (e[2] * x + e[6] * y + e[10] * z + e[14]) / w
    };
  }

  static transformNormal(n, matrix) {
    const e = matrix.elements;
    const x = n.x, y = n.y, z = n.z;
    const nx = e[0] * x + e[4] * y + e[8] * z;
    const ny = e[1] * x + e[5] * y + e[9] * z;
    const nz = e[2] * x + e[6] * y + e[10] * z;
    const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
    if (len > 0) {
      return { x: nx / len, y: ny / len, z: nz / len };
    }
    return { x: nx, y: ny, z: nz };
  }

  static download(meshes, filename = 'lsystem-plant.obj') {
    const content = this.export(meshes);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
